### ISSUE TITLE
[TW-643] Taskwarrior 2.0.0 can not build on Debian Linux 6.0

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#678]
_Alexei Romanoff on 2011-04-07T09:28:13Z says:_ 

 I've just pull taskwarrior from 2.0.0 branch and have tried to build the project. 
$cmake .
...
all right
$ make
...
[  2%] Building CXX object src/CMakeFiles/task.dir/Variant.cpp.o
/home/dr/devel/task.git/src/Variant.cpp:29:18: error: Text.h: No such file or directory
/home/dr/devel/task.git/src/Variant.cpp: In member function Variant& Variant::operator<=(const Variant&):
/home/dr/devel/task.git/src/Variant.cpp:153: error: strcmp was not declared in this scope
/home/dr/devel/task.git/src/Variant.cpp: In member function Variant& Variant::operator>=(const Variant&):
/home/dr/devel/task.git/src/Variant.cpp:190: error: strcmp was not declared in this scope
/home/dr/devel/task.git/src/Variant.cpp: In member function Variant& Variant::operator==(const Variant&):
/home/dr/devel/task.git/src/Variant.cpp:227: error: strcmp was not declared in this scope
/home/dr/devel/task.git/src/Variant.cpp: In member function Variant& Variant::operator!=(const Variant&):
/home/dr/devel/task.git/src/Variant.cpp:264: error: strcmp was not declared in this scope
/home/dr/devel/task.git/src/Variant.cpp: In member function Variant& Variant::operator<(const Variant&):
/home/dr/devel/task.git/src/Variant.cpp:478: error: strcmp was not declared in this scope
/home/dr/devel/task.git/src/Variant.cpp: In member function Variant& Variant::operator>(const Variant&):
/home/dr/devel/task.git/src/Variant.cpp:515: error: strcmp was not declared in this scope
/home/dr/devel/task.git/src/Variant.cpp: In member function void Variant::input(const std::string&):
/home/dr/devel/task.git/src/Variant.cpp:631: error: compare was not declared in this scope
/home/dr/devel/task.git/src/Variant.cpp:641: error: compare was not declared in this scope
/home/dr/devel/task.git/src/Variant.cpp:667: error: atof was not declared in this scope
/home/dr/devel/task.git/src/Variant.cpp:672: error: atoi was not declared in this scope
/home/dr/devel/task.git/src/Variant.cpp: In member function void Variant::cast(Variant::variant_type):
/home/dr/devel/task.git/src/Variant.cpp:785: error: atol was not declared in this scope
/home/dr/devel/task.git/src/Variant.cpp:788: error: atol was not declared in this scope
make[2]: *** [src/CMakeFiles/task.dir/Variant.cpp.o] Error 1
make[1]: *** [src/CMakeFiles/task.dir/all] Error 2
make: *** [all] Error 2

Result of build made me unhappy. After a short investigation I understood a problem and fixed it. The patch is attached, but I'm not sure. 
May be file 'text.h'  should be renamed to 'Text.h' in the repo. 

Additional info: 
$ gcc --version
gcc (Debian 4.4.5-8) 4.4.5
$ cmake --version
cmake version 2.8.2
$ git describe                                     
Post194ToMaster-44-gf7881f1

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2011-04-07T09:28:13Z
Modified: 2014-02-09T02:06:31Z
```

**Comment by taskwarrior** [comment]
_Alexei Romanoff on 2011-04-07T09:28:14Z says:_ 

 Attachment 0001-Fixed-build-errors-on-Debian-Linux.patch has been added with description: the patch

**Comment by taskwarrior** [comment]
_Federico Hernandez on 2011-04-07T10:35:20Z says:_ 

 Thanks Alexei for your concerns. But this is not a bug in the typical sense. 2.0.0 is a development version where things might not (yet) work, due to the fact that the feature is not ready implemented or not implemented/tested on all platforms. We may, as well, also deliberately break things on purpose. We appreciate your patch and will look through it. A better way would be to contact us directly to submit a patch and request feedback.

Please be aware, as 2.0.0 is a dev version, that you should backup your data as data loss might be possible!

**Comment by pbeckingham** [comment]
[TW-643_0001-Fixed-build-errors-on-Debian-Linux.patch.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1756196/TW-643_0001-Fixed-build-errors-on-Debian-Linux.patch.txt)
