### ISSUE TITLE
[TW-1579] 2.4.2 does not compile on OpenBSD

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#1605]
_Florian Baumann on 2015-03-22T19:30:30Z says:_ 

 Hi,

taskwarrior-2.4.2 does not compile on OpenBSD (5.6), while taskwarrior-2.4.0 still does. 

I'm not a C++ Programmer, so I attached the make log.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2015-03-22T19:30:30Z
Modified: 2015-03-30T19:06:45Z
```

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2015-03-22T22:17:32Z says:_ 

 This is telling:

```
CMakeFiles/calc_executable.dir/calc.cpp.o(.text+0x11e): In function `main':
: undefined reference to `std::cout'
```

It appears you are building with gcc, but with no g\+\+.  Is g\+\+ installed?

**Comment by taskwarrior** [comment]
_Wim Schuermann on 2015-03-23T07:40:33Z says:_ 

 I'd be more interested in your CMake output; if your g++ is actually gcc as Paul said, it should fail before ever allowing you to run make. If it doesn't, maybe we'll need to do something about that.

For the record, I just tried compiling the master branch (so 2.4.2 stable at this point in time) on OpenBSD 5.6 using g++-4.9.0p0 from packages, and it worked fine using:

```
CXX=eg++ cmake .
make
```

**Comment by taskwarrior** [comment]
_Florian Baumann on 2015-03-29T18:28:07Z says:_ 

 Hi,

sorry for the late reply... 


{code}
20:26 noqqe(at)noc:~/Code/task/task-2.4.2 $ CXX=eg++ cmake .
CMAKE_SYSTEM_NAME OpenBSD
* - Performing Test _HAS_CXX11
* - Performing Test _HAS_CXX11 - Success
* - Performing Test _HAS_CXX0X
* - Performing Test _HAS_CXX0X - Success
* - Performing Test _HAS_GNU0X
* - Performing Test _HAS_GNU0X - Success
* - Looking for SHA1 references
* - Looking for GnuTLS
* - Found GnuTLS: /usr/local/lib/libgnutls.so.41.4 (found version "3.2.15")
* - Looking for timegm
* - Looking for timegm - found
* - Looking for get_current_dir_name
* - Looking for get_current_dir_name - not found
* - Looking for wordexp
* - Looking for wordexp - not found
* - Performing Test HAVE_TM_GMTOFF
* - Performing Test HAVE_TM_GMTOFF - Success
* - Performing Test HAVE_ST_BIRTHTIME
* - Performing Test HAVE_ST_BIRTHTIME - Failed
* - Looking for libuuid
* - Looking for uuid_unparse_lower
* - Looking for uuid_unparse_lower - found
* - Found libuuid
* - Configuring cmake.h
* - Configuring man pages
* - Configuring done
* - Generating done
* - Build files have been written to: /home/noqqe/Code/task/task-2.4.2
{code}

and
{code}
20:27 noqqe(at)noc:~/Code/task/task-2.4.2 $ eg++ --version
eg++ (GCC) 4.9.0
Copyright (C) 2014 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
{code}

make does still have the same output :(
Should i upload it again ?

**Comment by taskwarrior** [comment]
_Wim Schuermann on 2015-03-29T20:48:28Z says:_ 

 Try
```
rm -rf CMakeFiles
CXX=eg++ cmake .
make
```

Or just restart from a freshly unpacked 2.4.2 tarball. CMake caches your C++ compiler, so it was silently using your system g++. If you want to catch it in the act, try
```
VERBOSE=1 make
```
and pay close attention to which compiler is used.

*EDIT*:
The nicer way to do this would probably be
```
cmake . -DCMAKE_CXX_COMPILER=eg++
make
```
since CMake is smart enough to detect that it needs to re-run the config step in that case.

**Comment by taskwarrior** [comment]
_Florian Baumann on 2015-03-30T05:47:16Z says:_ 

 ah, ive only deleted CMakeCache.txt and did cmake + make.

That worked. Thanks!

**Comment by taskwarrior** [comment]
_Wim Schuermann on 2015-03-30T19:06:45Z says:_ 

 Thank you for reporting this anyway, installing OpenBSD to test this made for an interesting lunch project. ;)

**Comment by pbeckingham** [comment]
[TW-1579_log.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1756392/TW-1579_log.txt)
