### ISSUE TITLE
[TW-1733] taskwarrior 2.5.0 can not compile FreeBSD 10.1

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#1757]
_ribbon on 2015-12-07T11:30:25Z says:_ 

 Taskwarrior 2.5.0 can not compile on FreeBSD 10.1

Error message is

% make
Scanning dependencies of target task
[  0%] Building CXX object src/CMakeFiles/task.dir/CLI2.cpp.o
[  1%] Building CXX object src/CMakeFiles/task.dir/Color.cpp.o
In file included from /home/ribbon/task-2.5.0/src/Color.cpp:33:
In file included from /home/ribbon/task-2.5.0/src/main.h:35:
/home/ribbon/task-2.5.0/src/ISO8601.h:100:12: error: class member cannot be redeclared
  ISO8601d operator+  (const int);
           ^
/home/ribbon/task-2.5.0/src/ISO8601.h:99:12: note: previous declaration is here
  ISO8601d operator+  (time_t);
           ^
1 error generated.
*** Error code 1

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2015-12-07T11:30:25Z
Modified: 2015-12-23T13:08:25Z
```

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2015-12-07T17:08:16Z says:_ 

 We only test with FreeBSD9.  What compiler/version are you using on 10.1?

Correction: we use FreeBSD10.

**Comment by taskwarrior** [comment]
_ribbon on 2015-12-16T08:09:54Z says:_ 

 I use this.

% cc --version
FreeBSD clang version 3.4.1 (tags/RELEASE_34/dot1-final 208032) 20140512
Target: i386-unknown-freebsd10.1
Thread model: posix

**Comment by taskwarrior** [comment]
_Wim Schuermann on 2015-12-22T18:00:21Z says:_ 

 This is TW-1596 all over again - 32bit FreeBSD uses the same underlying type for int and type_t, __int32_t.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2015-12-23T13:08:25Z says:_ 

 The overloaded method is not actually needed, so this was simply removed.
